name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
no-changes-template: "- No changes"
categories:
  - title: "Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "Bug Fixes"
    labels:
      - "bug"
      - "fix"
  - title: "Documentation"
    labels:
      - "docs"
      - "documentation"
  - title: "Refactors"
    labels:
      - "refactor"
  - title: "Tests"
    labels:
      - "test"
  - title: "CI"
    labels:
      - "ci"
  - title: "Chores"
    labels:
      - "chore"
      - "maintenance"
exclude-labels:
  - "skip-changelog"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Changes
  $CHANGES
